### ISSUE TITLE
What's the difference to pux?

### ISSUE THREAD

**Issue by timdeputter** [grmble/purescript-bonsai#14]
Hi,

your project looks really cool. I'm just curious: What makes it different from purescript-pux?

**Comment by grmble** [comment]
Bonsai targets the Elm Virtual Dom.

Other than that, the projects seem to be very similliar.  Pux seems to be able to use Smolder unchanged.  Bonsai encodes the type of emitted messages in the type of VDom nodes (the Elm Virtual Dom kind of expects you to), so I had to make my own version.

Edit:  I confused Pux with some other framework in my initial response. Sorry about that

**Comment by timdeputter** [comment]
No problem, thx for your detailed response.
