### ISSUE TITLE
Minimal example of running program

### ISSUE THREAD

**Issue by adicirstei** [grmble/purescript-bonsai#7]
Hi, 

Just one question:

Does it happens to have a minimal working example?
```purs
module Examples.Counter where

import Prelude
import Bonsai (domElementById, program, text)
import Bonsai.Types (Cmd(..))
import Control.Monad.Eff.Console (error)
import DOM.Node.Types (ElementId(..))
import Data.Maybe (Maybe(..))


data Msg = Inc | Dec

type Model = Int

programContainer = do
  domElementById $ ElementId "counter"

initialState :: Model
initialState = 0

update model msg = { model : model, cmd : NoCmd }

view = show >>> text

main = do
  mContainer <- programContainer
  
  case mContainer of 
    Just c -> program c update view initialState
    Nothing -> error "no container with specified id"
```
I came up with this, so far, but not sure how to go further

Thanks!

**Comment by grmble** [comment]
Funny you would choose a counter as example, that was the very first thing I tried :) 445f345c64d5284cc6f6f52dc58ce9e0550c0c0d

Your example looks like it would work, not sure what you question is?  If you add an html page you should be good to go.  Or do you get an error message?

Edit: Never mind, I see it is not complete. I'll add a minimal program to the README

**Comment by adicirstei** [comment]
It is not compiling due to error call at the end.

Type mismatch.

**Comment by grmble** [comment]
I changed the README to include a minimal example  - see  abf5d3aca677b66114f8464395a4d0239490ffed

Is this what you had in mind?

**Comment by adicirstei** [comment]
Thanks!

I'll give it a try when I'll get to a computer.
